export type ExtraMakerProductSeed = {
  title: string;
  slug: string;
  description: string;
  sku: string;
  priceCents: number;
  stockQty: number;
  media: Array<{ url: string; alt: string; storageKey: string; sortOrder: number }>;
};

export type ExtraMakerSeed = {
  email: string;
  name: string;
  displayName: string;
  slug: string;
  bio: string;
  city: string;
  craftTags: string[];
  categorySlug: 'pottery' | 'jewelry' | 'woodwork' | 'textiles' | 'food-crafts';
  bannerUrl: string;
  logoUrl: string;
  shipsFromCity: string;
  flatShippingCents: number;
  products: ExtraMakerProductSeed[];
};

const u = (id: string, w: number) => `https://images.unsplash.com/photo-${id}?w=${w}&q=80`;
const p = (id: number, w: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`;

/** Twenty additional approved makers with catalog products for demo density. */
export const EXTRA_MAKERS: ExtraMakerSeed[] = [
  {
    email: 'kiln-co@crafthub.local',
    name: 'Raza Kiln',
    displayName: 'Kiln & Co.',
    slug: 'kiln-co',
    bio: 'Functional stoneware fired in a shared studio kiln in Karachi — mugs, plates, and serving pieces.',
    city: 'Karachi',
    craftTags: ['pottery', 'stoneware', 'kitchen'],
    categorySlug: 'pottery',
    bannerUrl: u('1578662996442-48f60103fc96', 1600),
    logoUrl: u('1578749556568-bc2c40e68b61', 200),
    shipsFromCity: 'Karachi',
    flatShippingCents: 420,
    products: [
      {
        title: 'Morning Tea Cup',
        slug: 'morning-tea-cup',
        description: 'Stoneware tea cup with a comfortable handle. About 250ml.',
        sku: 'KILN-TEA-01',
        priceCents: 2400,
        stockQty: 30,
        media: [{ url: u('1514228742587-6b1558fcca3d', 800), alt: 'Stoneware tea cup', storageKey: 'seed/kiln/tea-1', sortOrder: 0 }],
      },
      {
        title: 'Matcha Bowl',
        slug: 'matcha-bowl',
        description: 'Wide matcha bowl with a foot ring and soft grey glaze.',
        sku: 'KILN-MAT-01',
        priceCents: 3200,
        stockQty: 16,
        media: [{ url: u('1610701596007-11502861dcfa', 800), alt: 'Ceramic matcha bowl', storageKey: 'seed/kiln/matcha-1', sortOrder: 0 }],
      },
      {
        title: 'Pitcher Small',
        slug: 'pitcher-small',
        description: 'Compact ceramic pitcher for milk or cream. About 400ml.',
        sku: 'KILN-PIT-01',
        priceCents: 3800,
        stockQty: 12,
        media: [{ url: p(1123401, 800), alt: 'Small ceramic pitcher', storageKey: 'seed/kiln/pitcher-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'silver-thread@crafthub.local',
    name: 'Sana Thread',
    displayName: 'Silver Thread Studio',
    slug: 'silver-thread',
    bio: 'Fine silver chains and everyday pieces handmade in Lahore.',
    city: 'Lahore',
    craftTags: ['jewelry', 'silver', 'chains'],
    categorySlug: 'jewelry',
    bannerUrl: u('1515562141207-7a88fb7ce338', 1600),
    logoUrl: u('1605100804763-247f67b3557e', 200),
    shipsFromCity: 'Lahore',
    flatShippingCents: 380,
    products: [
      {
        title: 'Fine Chain Necklace',
        slug: 'fine-chain-necklace',
        description: 'Delicate sterling chain, 45cm with spring clasp.',
        sku: 'ST-NECK-01',
        priceCents: 4800,
        stockQty: 14,
        media: [{ url: u('1599643478518-a784e5dc4c8f', 800), alt: 'Fine silver chain necklace', storageKey: 'seed/st/neck-1', sortOrder: 0 }],
      },
      {
        title: 'Hoop Earrings Medium',
        slug: 'hoop-earrings-medium',
        description: 'Classic sterling hoops, 25mm diameter.',
        sku: 'ST-HOOP-01',
        priceCents: 3600,
        stockQty: 20,
        media: [{ url: p(1191531, 800), alt: 'Silver hoop earrings', storageKey: 'seed/st/hoop-1', sortOrder: 0 }],
      },
      {
        title: 'Birthstone Ring',
        slug: 'birthstone-ring',
        description: 'Sterling band with a small faceted stone. Sizes 6–9.',
        sku: 'ST-RING-01',
        priceCents: 5800,
        stockQty: 10,
        media: [{ url: u('1603561596112-0a132b757442', 800), alt: 'Birthstone silver ring', storageKey: 'seed/st/ring-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'timber-folk@crafthub.local',
    name: 'Bilal Timber',
    displayName: 'Timber Folk',
    slug: 'timber-folk',
    bio: 'Small-batch wooden kitchenware from a home workshop in Islamabad.',
    city: 'Islamabad',
    craftTags: ['woodwork', 'kitchen', 'handmade'],
    categorySlug: 'woodwork',
    bannerUrl: u('1556909114-f6e7ad7d3136', 1600),
    logoUrl: u('1556911220-bff31c812dba', 200),
    shipsFromCity: 'Islamabad',
    flatShippingCents: 550,
    products: [
      {
        title: 'Ash Cutting Board',
        slug: 'ash-cutting-board',
        description: 'Edge-grain ash board with juice groove. About 35×25cm.',
        sku: 'TF-BOARD-01',
        priceCents: 5200,
        stockQty: 15,
        media: [{ url: u('1606914469633-bd39206ea739', 800), alt: 'Ash cutting board', storageKey: 'seed/tf/board-1', sortOrder: 0 }],
      },
      {
        title: 'Walnut Mortar',
        slug: 'walnut-mortar',
        description: 'Hand-turned walnut mortar for spices. About 10cm.',
        sku: 'TF-MORT-01',
        priceCents: 3400,
        stockQty: 18,
        media: [{ url: p(6944172, 800), alt: 'Walnut mortar', storageKey: 'seed/tf/mortar-1', sortOrder: 0 }],
      },
      {
        title: 'Cedar Coasters (4)',
        slug: 'cedar-coasters',
        description: 'Set of four cedar coasters with felt pads.',
        sku: 'TF-COAST-04',
        priceCents: 2200,
        stockQty: 25,
        media: [{ url: p(4397920, 800), alt: 'Cedar coasters', storageKey: 'seed/tf/coast-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'weave-house@crafthub.local',
    name: 'Nadia Weave',
    displayName: 'Weave House',
    slug: 'weave-house',
    bio: 'Handloom textiles and soft home goods woven in Faisalabad.',
    city: 'Faisalabad',
    craftTags: ['textiles', 'weaving', 'home'],
    categorySlug: 'textiles',
    bannerUrl: u('1558171813-4c088753af8f', 1600),
    logoUrl: u('1582735689369-4fe89db7114c', 200),
    shipsFromCity: 'Faisalabad',
    flatShippingCents: 480,
    products: [
      {
        title: 'Cotton Throw Blanket',
        slug: 'cotton-throw-blanket',
        description: 'Soft cotton throw with subtle stripe. About 130×170cm.',
        sku: 'WH-THROW-01',
        priceCents: 7200,
        stockQty: 10,
        media: [{ url: u('1616486338812-3dadae4b4ace', 800), alt: 'Cotton throw blanket', storageKey: 'seed/wh/throw-1', sortOrder: 0 }],
      },
      {
        title: 'Handloom Placemat',
        slug: 'handloom-placemat',
        description: 'Single handloom placemat with fringe. About 35×45cm.',
        sku: 'WH-PLACE-01',
        priceCents: 1800,
        stockQty: 32,
        media: [{ url: p(1090638, 800), alt: 'Handloom placemat', storageKey: 'seed/wh/place-1', sortOrder: 0 }],
      },
      {
        title: 'Woven Wall Hanging',
        slug: 'woven-wall-hanging',
        description: 'Small wall hanging with natural cotton and wool blend.',
        sku: 'WH-WALL-01',
        priceCents: 5600,
        stockQty: 8,
        media: [{ url: p(6585764, 800), alt: 'Woven wall hanging', storageKey: 'seed/wh/wall-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'mountain-harvest@crafthub.local',
    name: 'Tariq Harvest',
    displayName: 'Mountain Harvest',
    slug: 'mountain-harvest',
    bio: 'Preserved fruit and mountain herbs from Abbottabad orchards.',
    city: 'Abbottabad',
    craftTags: ['food', 'preserves', 'herbs'],
    categorySlug: 'food-crafts',
    bannerUrl: p(1092730, 1600),
    logoUrl: p(1638280, 200),
    shipsFromCity: 'Abbottabad',
    flatShippingCents: 520,
    products: [
      {
        title: 'Plum Chutney 300g',
        slug: 'plum-chutney',
        description: 'Tangy plum chutney with warm spice. Glass jar, 300g.',
        sku: 'MH-CHUT-300',
        priceCents: 1700,
        stockQty: 40,
        media: [{ url: p(4198024, 800), alt: 'Plum chutney jar', storageKey: 'seed/mh/chut-1', sortOrder: 0 }],
      },
      {
        title: 'Mountain Herb Tea',
        slug: 'mountain-herb-tea',
        description: 'Loose-leaf herbal blend, 80g pouch.',
        sku: 'MH-TEA-80',
        priceCents: 1300,
        stockQty: 55,
        media: [{ url: p(4198019, 800), alt: 'Herbal tea pouch', storageKey: 'seed/mh/tea-1', sortOrder: 0 }],
      },
      {
        title: 'Apple Butter 250g',
        slug: 'apple-butter',
        description: 'Slow-cooked apple butter. Glass jar, 250g.',
        sku: 'MH-APPLE-250',
        priceCents: 1600,
        stockQty: 36,
        media: [{ url: p(5591663, 800), alt: 'Apple butter jar', storageKey: 'seed/mh/apple-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'clay-path@crafthub.local',
    name: 'Mehwish Clay',
    displayName: 'Clay Path Studio',
    slug: 'clay-path',
    bio: 'Earthy tableware and planters thrown on a kick wheel in Rawalpindi.',
    city: 'Rawalpindi',
    craftTags: ['pottery', 'planters', 'tableware'],
    categorySlug: 'pottery',
    bannerUrl: u('1565193566173-7a0ee3dbe261', 1600),
    logoUrl: u('1493106819501-66d381c466f1', 200),
    shipsFromCity: 'Rawalpindi',
    flatShippingCents: 400,
    products: [
      {
        title: 'Terracotta Planter',
        slug: 'terracotta-planter',
        description: 'Unglazed terracotta planter with drainage hole. About 15cm.',
        sku: 'CP-PLANT-01',
        priceCents: 2200,
        stockQty: 22,
        media: [{ url: p(896923, 800), alt: 'Terracotta planter', storageKey: 'seed/cp/plant-1', sortOrder: 0 }],
      },
      {
        title: 'Cereal Bowl Set',
        slug: 'cereal-bowl-set',
        description: 'Pair of cereal bowls with satin white glaze.',
        sku: 'CP-BOWL-02',
        priceCents: 4400,
        stockQty: 14,
        media: [{ url: u('1493106819501-66d381c466f1', 800), alt: 'Cereal bowl set', storageKey: 'seed/cp/bowl-1', sortOrder: 0 }],
      },
      {
        title: 'Salt Cellar',
        slug: 'salt-cellar',
        description: 'Small lidded salt cellar with spoon rest.',
        sku: 'CP-SALT-01',
        priceCents: 1900,
        stockQty: 26,
        media: [{ url: u('1514228742587-6b1558fcca3d', 800), alt: 'Ceramic salt cellar', storageKey: 'seed/cp/salt-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'gem-wire@crafthub.local',
    name: 'Farah Gem',
    displayName: 'Gem & Wire',
    slug: 'gem-wire',
    bio: 'Wire-wrapped stones and bold statement pieces from Quetta.',
    city: 'Quetta',
    craftTags: ['jewelry', 'stones', 'wire-wrap'],
    categorySlug: 'jewelry',
    bannerUrl: u('1611598187929-2a416902242e', 1600),
    logoUrl: u('1603561596112-0a132b757442', 200),
    shipsFromCity: 'Quetta',
    flatShippingCents: 400,
    products: [
      {
        title: 'Agate Pendant',
        slug: 'agate-pendant',
        description: 'Wire-wrapped agate slice on a leather cord.',
        sku: 'GW-PEND-01',
        priceCents: 4200,
        stockQty: 12,
        media: [{ url: u('1605100804763-247f67b3557e', 800), alt: 'Agate pendant necklace', storageKey: 'seed/gw/pend-1', sortOrder: 0 }],
      },
      {
        title: 'Turquoise Studs',
        slug: 'turquoise-studs',
        description: 'Sterling studs with small turquoise cabochons.',
        sku: 'GW-STUD-01',
        priceCents: 2900,
        stockQty: 18,
        media: [{ url: p(1191531, 800), alt: 'Turquoise stud earrings', storageKey: 'seed/gw/stud-1', sortOrder: 0 }],
      },
      {
        title: 'Statement Cuff',
        slug: 'statement-cuff',
        description: 'Wide hammered cuff with an oxidized finish.',
        sku: 'GW-CUFF-01',
        priceCents: 6800,
        stockQty: 7,
        media: [{ url: u('1599643478518-a784e5dc4c8f', 800), alt: 'Statement silver cuff', storageKey: 'seed/gw/cuff-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'oak-ash@crafthub.local',
    name: 'Hamza Oak',
    displayName: 'Oak & Ash',
    slug: 'oak-ash',
    bio: 'Furniture accents and carved boxes from Sialkot hardwood offcuts.',
    city: 'Sialkot',
    craftTags: ['woodwork', 'boxes', 'furniture'],
    categorySlug: 'woodwork',
    bannerUrl: u('1504148455328-081786aed1fc', 1600),
    logoUrl: u('1606914469633-bd39206ea739', 200),
    shipsFromCity: 'Sialkot',
    flatShippingCents: 620,
    products: [
      {
        title: 'Keepsake Box',
        slug: 'keepsake-box',
        description: 'Hinged walnut keepsake box with brass clasp.',
        sku: 'OA-BOX-01',
        priceCents: 6400,
        stockQty: 9,
        media: [{ url: p(4226896, 800), alt: 'Walnut keepsake box', storageKey: 'seed/oa/box-1', sortOrder: 0 }],
      },
      {
        title: 'Bookends Pair',
        slug: 'bookends-pair',
        description: 'Matched oak bookends with a live edge.',
        sku: 'OA-BOOK-02',
        priceCents: 5800,
        stockQty: 11,
        media: [{ url: u('1556909114-f6e7ad7d3136', 800), alt: 'Oak bookends', storageKey: 'seed/oa/book-1', sortOrder: 0 }],
      },
      {
        title: 'Desk Organizer',
        slug: 'desk-organizer',
        description: 'Compact desk organizer with pen slots and tray.',
        sku: 'OA-DESK-01',
        priceCents: 4600,
        stockQty: 13,
        media: [{ url: u('1606914469633-bd39206ea739', 800), alt: 'Wooden desk organizer', storageKey: 'seed/oa/desk-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'indigo-loom@crafthub.local',
    name: 'Sadia Indigo',
    displayName: 'Indigo Loom',
    slug: 'indigo-loom',
    bio: 'Naturally dyed scarves and wraps from a family loom in Hyderabad.',
    city: 'Hyderabad',
    craftTags: ['textiles', 'indigo', 'scarves'],
    categorySlug: 'textiles',
    bannerUrl: u('1601924994987-69e26d50dc26', 1600),
    logoUrl: u('1601924994987-69e26d50dc26', 200),
    shipsFromCity: 'Hyderabad',
    flatShippingCents: 460,
    products: [
      {
        title: 'Shibori Scarf',
        slug: 'shibori-scarf',
        description: 'Cotton scarf with resist-dyed shibori pattern. 180×50cm.',
        sku: 'IL-SCARF-01',
        priceCents: 3400,
        stockQty: 19,
        media: [{ url: u('1601924994987-69e26d50dc26', 800), alt: 'Shibori indigo scarf', storageKey: 'seed/il/scarf-1', sortOrder: 0 }],
      },
      {
        title: 'Indigo Bandana',
        slug: 'indigo-bandana',
        description: 'Square bandana in deep indigo. 55×55cm.',
        sku: 'IL-BAND-01',
        priceCents: 1600,
        stockQty: 28,
        media: [{ url: p(6969831, 800), alt: 'Indigo bandana', storageKey: 'seed/il/band-1', sortOrder: 0 }],
      },
      {
        title: 'Wrap Shawl',
        slug: 'wrap-shawl',
        description: 'Lightweight cotton shawl with gradient dye. 200×70cm.',
        sku: 'IL-SHAWL-01',
        priceCents: 4800,
        stockQty: 12,
        media: [{ url: p(6585764, 800), alt: 'Indigo wrap shawl', storageKey: 'seed/il/shawl-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'spice-jar@crafthub.local',
    name: 'Khalid Spice',
    displayName: 'Spice Jar Co.',
    slug: 'spice-jar',
    bio: 'Small-batch spice blends and infused oils from coastal Gwadar.',
    city: 'Gwadar',
    craftTags: ['food', 'spices', 'oils'],
    categorySlug: 'food-crafts',
    bannerUrl: p(2255935, 1600),
    logoUrl: p(2255935, 200),
    shipsFromCity: 'Gwadar',
    flatShippingCents: 580,
    products: [
      {
        title: 'Coastal Spice Blend',
        slug: 'coastal-spice-blend',
        description: 'House spice mix for fish and rice. Glass jar, 100g.',
        sku: 'SJ-SPICE-100',
        priceCents: 1200,
        stockQty: 50,
        media: [{ url: p(2255935, 800), alt: 'Coastal spice blend jar', storageKey: 'seed/sj/spice-1', sortOrder: 0 }],
      },
      {
        title: 'Garlic Infused Oil',
        slug: 'garlic-infused-oil',
        description: 'Cold-infused garlic oil. Glass bottle, 250ml.',
        sku: 'SJ-OIL-250',
        priceCents: 1900,
        stockQty: 34,
        media: [{ url: p(4198024, 800), alt: 'Garlic infused oil', storageKey: 'seed/sj/oil-1', sortOrder: 0 }],
      },
      {
        title: 'Smoked Paprika',
        slug: 'smoked-paprika',
        description: 'Slow-smoked paprika powder. Tin, 80g.',
        sku: 'SJ-PAP-80',
        priceCents: 1100,
        stockQty: 42,
        media: [{ url: p(4198019, 800), alt: 'Smoked paprika tin', storageKey: 'seed/sj/pap-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'earth-forms@crafthub.local',
    name: 'Layla Earth',
    displayName: 'Earth Forms',
    slug: 'earth-forms',
    bio: 'Sculptural vases and organic forms from a Peshawar clay studio.',
    city: 'Peshawar',
    craftTags: ['pottery', 'vases', 'sculptural'],
    categorySlug: 'pottery',
    bannerUrl: u('1578662996442-48f60103fc96', 1600),
    logoUrl: u('1610701596007-11502861dcfa', 200),
    shipsFromCity: 'Peshawar',
    flatShippingCents: 450,
    products: [
      {
        title: 'Sculptural Vase',
        slug: 'sculptural-vase',
        description: 'Asymmetric vase with matte exterior glaze. About 30cm.',
        sku: 'EF-VASE-01',
        priceCents: 6200,
        stockQty: 6,
        media: [{ url: p(1123401, 800), alt: 'Sculptural ceramic vase', storageKey: 'seed/ef/vase-1', sortOrder: 0 }],
      },
      {
        title: 'Textured Mug',
        slug: 'textured-mug',
        description: 'Hand-built mug with thumb-pressed texture.',
        sku: 'EF-MUG-01',
        priceCents: 2600,
        stockQty: 20,
        media: [{ url: u('1514228742587-6b1558fcca3d', 800), alt: 'Textured ceramic mug', storageKey: 'seed/ef/mug-1', sortOrder: 0 }],
      },
      {
        title: 'Serving Platter',
        slug: 'serving-platter',
        description: 'Wide oval platter with speckled glaze. About 32cm.',
        sku: 'EF-PLAT-01',
        priceCents: 4800,
        stockQty: 10,
        media: [{ url: p(896923, 800), alt: 'Ceramic serving platter', storageKey: 'seed/ef/plat-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'moon-metal@crafthub.local',
    name: 'Zara Moon',
    displayName: 'Moon Metal',
    slug: 'moon-metal',
    bio: 'Minimalist silver jewelry inspired by lunar shapes, made in Multan.',
    city: 'Multan',
    craftTags: ['jewelry', 'minimal', 'silver'],
    categorySlug: 'jewelry',
    bannerUrl: u('1611598187929-2a416902242e', 1600),
    logoUrl: u('1605100804763-247f67b3557e', 200),
    shipsFromCity: 'Multan',
    flatShippingCents: 360,
    products: [
      {
        title: 'Crescent Necklace',
        slug: 'crescent-necklace',
        description: 'Fine silver crescent on a delicate chain.',
        sku: 'MM-CRES-01',
        priceCents: 5200,
        stockQty: 11,
        media: [{ url: u('1599643478518-a784e5dc4c8f', 800), alt: 'Crescent silver necklace', storageKey: 'seed/mm/cres-1', sortOrder: 0 }],
      },
      {
        title: 'Orb Studs',
        slug: 'orb-studs',
        description: 'Tiny domed silver studs with mirror polish.',
        sku: 'MM-ORB-01',
        priceCents: 2400,
        stockQty: 22,
        media: [{ url: p(1191531, 800), alt: 'Silver orb stud earrings', storageKey: 'seed/mm/orb-1', sortOrder: 0 }],
      },
      {
        title: 'Lunar Band',
        slug: 'lunar-band',
        description: 'Slightly domed band ring with satin finish.',
        sku: 'MM-BAND-01',
        priceCents: 4400,
        stockQty: 13,
        media: [{ url: u('1603561596112-0a132b757442', 800), alt: 'Lunar silver band ring', storageKey: 'seed/mm/band-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'hand-plane@crafthub.local',
    name: 'Usman Plane',
    displayName: 'Hand Plane Works',
    slug: 'hand-plane',
    bio: 'Traditional joinery and hand-planed boards from Gujranwala.',
    city: 'Gujranwala',
    craftTags: ['woodwork', 'joinery', 'boards'],
    categorySlug: 'woodwork',
    bannerUrl: u('1504148455328-081786aed1fc', 1600),
    logoUrl: u('1556911220-bff31c812dba', 200),
    shipsFromCity: 'Gujranwala',
    flatShippingCents: 600,
    products: [
      {
        title: 'Bread Board Long',
        slug: 'bread-board-long',
        description: 'Long maple bread board with handle cutout.',
        sku: 'HP-BREAD-01',
        priceCents: 4200,
        stockQty: 14,
        media: [{ url: u('1606914469633-bd39206ea739', 800), alt: 'Long bread board', storageKey: 'seed/hp/bread-1', sortOrder: 0 }],
      },
      {
        title: 'Serving Paddle',
        slug: 'serving-paddle',
        description: 'Wide serving paddle in cherry wood.',
        sku: 'HP-PADDLE-01',
        priceCents: 3800,
        stockQty: 16,
        media: [{ url: p(6944172, 800), alt: 'Cherry serving paddle', storageKey: 'seed/hp/paddle-1', sortOrder: 0 }],
      },
      {
        title: 'Trivet Set',
        slug: 'trivet-set',
        description: 'Set of two interlocking hardwood trivets.',
        sku: 'HP-TRIV-02',
        priceCents: 2600,
        stockQty: 20,
        media: [{ url: p(4397920, 800), alt: 'Wooden trivet set', storageKey: 'seed/hp/triv-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'thread-needle@crafthub.local',
    name: 'Amira Thread',
    displayName: 'Thread & Needle',
    slug: 'thread-needle',
    bio: 'Embroidered linens and stitched home textiles from Bahawalpur.',
    city: 'Bahawalpur',
    craftTags: ['textiles', 'embroidery', 'linen'],
    categorySlug: 'textiles',
    bannerUrl: u('1558171813-4c088753af8f', 1600),
    logoUrl: u('1582735689369-4fe89db7114c', 200),
    shipsFromCity: 'Bahawalpur',
    flatShippingCents: 470,
    products: [
      {
        title: 'Embroidered Pillowcase',
        slug: 'embroidered-pillowcase',
        description: 'Cotton pillowcase with hand-embroidered border. Standard size.',
        sku: 'TN-PILLOW-01',
        priceCents: 3200,
        stockQty: 17,
        media: [{ url: p(1090638, 800), alt: 'Embroidered pillowcase', storageKey: 'seed/tn/pillow-1', sortOrder: 0 }],
      },
      {
        title: 'Linen Tablecloth',
        slug: 'linen-tablecloth',
        description: 'Natural linen tablecloth for four. About 140×140cm.',
        sku: 'TN-TABLE-01',
        priceCents: 7800,
        stockQty: 7,
        media: [{ url: u('1616486338812-3dadae4b4ace', 800), alt: 'Linen tablecloth', storageKey: 'seed/tn/table-1', sortOrder: 0 }],
      },
      {
        title: 'Stitched Coasters (6)',
        slug: 'stitched-coasters',
        description: 'Set of six embroidered fabric coasters.',
        sku: 'TN-COAST-06',
        priceCents: 2100,
        stockQty: 24,
        media: [{ url: p(6585764, 800), alt: 'Stitched fabric coasters', storageKey: 'seed/tn/coast-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'apiary-lane@crafthub.local',
    name: 'Hassan Apiary',
    displayName: 'Apiary Lane',
    slug: 'apiary-lane',
    bio: 'Raw honey and beeswax goods from Swat valley hives.',
    city: 'Swat',
    craftTags: ['food', 'honey', 'beeswax'],
    categorySlug: 'food-crafts',
    bannerUrl: p(1638280, 1600),
    logoUrl: p(5591663, 200),
    shipsFromCity: 'Swat',
    flatShippingCents: 540,
    products: [
      {
        title: 'Acacia Honey 350g',
        slug: 'acacia-honey-350',
        description: 'Light acacia honey in a glass jar. 350g.',
        sku: 'AL-HONEY-350',
        priceCents: 2200,
        stockQty: 38,
        media: [{ url: p(1638280, 800), alt: 'Acacia honey jar', storageKey: 'seed/al/honey-1', sortOrder: 0 }],
      },
      {
        title: 'Beeswax Candles (2)',
        slug: 'beeswax-candles',
        description: 'Pair of rolled beeswax taper candles.',
        sku: 'AL-CAND-02',
        priceCents: 1800,
        stockQty: 30,
        media: [{ url: p(5591663, 800), alt: 'Beeswax candles', storageKey: 'seed/al/cand-1', sortOrder: 0 }],
      },
      {
        title: 'Honeycomb Chunk',
        slug: 'honeycomb-chunk',
        description: 'Raw honeycomb section in a clear box. About 200g.',
        sku: 'AL-COMB-200',
        priceCents: 2600,
        stockQty: 22,
        media: [{ url: p(1092730, 800), alt: 'Raw honeycomb chunk', storageKey: 'seed/al/comb-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'studio-fire@crafthub.local',
    name: 'Iqbal Fire',
    displayName: 'Studio Fire',
    slug: 'studio-fire',
    bio: 'High-fire porcelain cups and table pieces from Sukkur.',
    city: 'Sukkur',
    craftTags: ['pottery', 'porcelain', 'cups'],
    categorySlug: 'pottery',
    bannerUrl: u('1565193566173-7a0ee3dbe261', 1600),
    logoUrl: u('1578749556568-bc2c40e68b61', 200),
    shipsFromCity: 'Sukkur',
    flatShippingCents: 430,
    products: [
      {
        title: 'Porcelain Espresso Cup',
        slug: 'porcelain-espresso-cup',
        description: 'Thin-walled porcelain espresso cup. About 80ml.',
        sku: 'SF-ESP-01',
        priceCents: 2100,
        stockQty: 24,
        media: [{ url: u('1493106819501-66d381c466f1', 800), alt: 'Porcelain espresso cup', storageKey: 'seed/sf/esp-1', sortOrder: 0 }],
      },
      {
        title: 'Latte Mug',
        slug: 'latte-mug',
        description: 'Wide porcelain mug for lattes. About 350ml.',
        sku: 'SF-LATTE-01',
        priceCents: 2900,
        stockQty: 18,
        media: [{ url: u('1514228742587-6b1558fcca3d', 800), alt: 'Porcelain latte mug', storageKey: 'seed/sf/latte-1', sortOrder: 0 }],
      },
      {
        title: 'Dessert Plate Pair',
        slug: 'dessert-plate-pair',
        description: 'Pair of small dessert plates with cobalt rim.',
        sku: 'SF-PLATE-02',
        priceCents: 3600,
        stockQty: 15,
        media: [{ url: p(896923, 800), alt: 'Porcelain dessert plates', storageKey: 'seed/sf/plate-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'pearl-chain@crafthub.local',
    name: 'Rubina Pearl',
    displayName: 'Pearl & Chain',
    slug: 'pearl-chain',
    bio: 'Pearl accents and layered necklaces from Mirpur.',
    city: 'Mirpur',
    craftTags: ['jewelry', 'pearls', 'necklaces'],
    categorySlug: 'jewelry',
    bannerUrl: u('1515562141207-7a88fb7ce338', 1600),
    logoUrl: u('1599643478518-a784e5dc4c8f', 200),
    shipsFromCity: 'Mirpur',
    flatShippingCents: 370,
    products: [
      {
        title: 'Pearl Layer Necklace',
        slug: 'pearl-layer-necklace',
        description: 'Two-strand freshwater pearl necklace, 40cm.',
        sku: 'PC-LAYER-01',
        priceCents: 7200,
        stockQty: 8,
        media: [{ url: u('1599643478518-a784e5dc4c8f', 800), alt: 'Layered pearl necklace', storageKey: 'seed/pc/layer-1', sortOrder: 0 }],
      },
      {
        title: 'Pearl Drop Earrings',
        slug: 'pearl-drop-earrings',
        description: 'Freshwater pearl drops on silver hooks.',
        sku: 'PC-DROP-01',
        priceCents: 4100,
        stockQty: 14,
        media: [{ url: p(1191531, 800), alt: 'Pearl drop earrings', storageKey: 'seed/pc/drop-1', sortOrder: 0 }],
      },
      {
        title: 'Pearl Bracelet',
        slug: 'pearl-bracelet',
        description: 'Single-strand pearl bracelet with silver clasp.',
        sku: 'PC-BRACE-01',
        priceCents: 5600,
        stockQty: 10,
        media: [{ url: u('1603561596112-0a132b757442', 800), alt: 'Pearl bracelet', storageKey: 'seed/pc/brace-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'root-craft@crafthub.local',
    name: 'Danish Root',
    displayName: 'Root Craft',
    slug: 'root-craft',
    bio: 'Carved roots and live-edge pieces from Muzaffarabad forests.',
    city: 'Muzaffarabad',
    craftTags: ['woodwork', 'carving', 'live-edge'],
    categorySlug: 'woodwork',
    bannerUrl: u('1556909114-f6e7ad7d3136', 1600),
    logoUrl: u('1556911220-bff31c812dba', 200),
    shipsFromCity: 'Muzaffarabad',
    flatShippingCents: 650,
    products: [
      {
        title: 'Live Edge Shelf',
        slug: 'live-edge-shelf',
        description: 'Single live-edge floating shelf, about 60cm.',
        sku: 'RC-SHELF-01',
        priceCents: 7800,
        stockQty: 6,
        media: [{ url: u('1504148455328-081786aed1fc', 800), alt: 'Live edge shelf', storageKey: 'seed/rc/shelf-1', sortOrder: 0 }],
      },
      {
        title: 'Root Bowl',
        slug: 'root-bowl',
        description: 'Carved root wood serving bowl, about 20cm.',
        sku: 'RC-BOWL-01',
        priceCents: 5400,
        stockQty: 9,
        media: [{ url: p(4226896, 800), alt: 'Root wood bowl', storageKey: 'seed/rc/bowl-1', sortOrder: 0 }],
      },
      {
        title: 'Carved Spoon Large',
        slug: 'carved-spoon-large',
        description: 'Large serving spoon from root burl.',
        sku: 'RC-SPOON-01',
        priceCents: 2800,
        stockQty: 16,
        media: [{ url: p(6944172, 800), alt: 'Carved root spoon', storageKey: 'seed/rc/spoon-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'natural-dye@crafthub.local',
    name: 'Kiran Dye',
    displayName: 'Natural Dye Co.',
    slug: 'natural-dye',
    bio: 'Plant-dyed fabrics and eco-print scarves from Larkana.',
    city: 'Larkana',
    craftTags: ['textiles', 'natural-dye', 'eco-print'],
    categorySlug: 'textiles',
    bannerUrl: u('1601924994987-69e26d50dc26', 1600),
    logoUrl: u('1582735689369-4fe89db7114c', 200),
    shipsFromCity: 'Larkana',
    flatShippingCents: 490,
    products: [
      {
        title: 'Eco Print Scarf',
        slug: 'eco-print-scarf',
        description: 'Silk-cotton scarf with leaf eco-prints. 180×45cm.',
        sku: 'ND-SCARF-01',
        priceCents: 4200,
        stockQty: 13,
        media: [{ url: p(6969831, 800), alt: 'Eco print scarf', storageKey: 'seed/nd/scarf-1', sortOrder: 0 }],
      },
      {
        title: 'Dyed Napkin Set',
        slug: 'dyed-napkin-set',
        description: 'Set of four plant-dyed cotton napkins.',
        sku: 'ND-NAP-04',
        priceCents: 2800,
        stockQty: 20,
        media: [{ url: u('1601924994987-69e26d50dc26', 800), alt: 'Plant-dyed napkins', storageKey: 'seed/nd/nap-1', sortOrder: 0 }],
      },
      {
        title: 'Botanical Tote',
        slug: 'botanical-tote',
        description: 'Canvas tote with botanical print panel.',
        sku: 'ND-TOTE-01',
        priceCents: 3400,
        stockQty: 15,
        media: [{ url: p(1090638, 800), alt: 'Botanical print tote', storageKey: 'seed/nd/tote-1', sortOrder: 0 }],
      },
    ],
  },
  {
    email: 'pantry-roots@crafthub.local',
    name: 'Yasmin Pantry',
    displayName: 'Pantry Roots',
    slug: 'pantry-roots',
    bio: 'Fermented pickles and pantry staples from Chitral kitchens.',
    city: 'Chitral',
    craftTags: ['food', 'pickles', 'pantry'],
    categorySlug: 'food-crafts',
    bannerUrl: p(1092730, 1600),
    logoUrl: p(4198024, 200),
    shipsFromCity: 'Chitral',
    flatShippingCents: 560,
    products: [
      {
        title: 'Mixed Pickle Jar',
        slug: 'mixed-pickle-jar',
        description: 'Traditional mixed vegetable pickle. Glass jar, 400g.',
        sku: 'PR-PICK-400',
        priceCents: 1500,
        stockQty: 44,
        media: [{ url: p(4198019, 800), alt: 'Mixed pickle jar', storageKey: 'seed/pr/pick-1', sortOrder: 0 }],
      },
      {
        title: 'Sour Cherry Jam',
        slug: 'sour-cherry-jam',
        description: 'Tart sour cherry preserve. Glass jar, 250g.',
        sku: 'PR-JAM-250',
        priceCents: 1700,
        stockQty: 32,
        media: [{ url: p(4198024, 800), alt: 'Sour cherry jam', storageKey: 'seed/pr/jam-1', sortOrder: 0 }],
      },
      {
        title: 'Walnut Oil 200ml',
        slug: 'walnut-oil',
        description: 'Cold-pressed walnut oil for salads. Glass bottle, 200ml.',
        sku: 'PR-OIL-200',
        priceCents: 2400,
        stockQty: 26,
        media: [{ url: p(5591663, 800), alt: 'Walnut oil bottle', storageKey: 'seed/pr/oil-1', sortOrder: 0 }],
      },
    ],
  },
];
